@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle bold

package "bookstore" {

    class User {
        id : int
        email : string
        firstName : string
        lastName : string
        phone : string
        dateOfBirth : DateTime
        password : string
        roles : array
        isVerified : bool
    }

    class Address {
        id : int
        user : User
        label : string
        streetLine1 : string
        streetLine2 : string
        city : string
        stateOrRegion : string
        postalCode : string
        countryCode : string
        additionalInfo : string
    }

    class Book {
        id : int
        title : string
        authors : array
        description : text
        isbn13 : string
        price : int
        stock : int
        coverUrl : string
        publishedAt : DateTime
        createdAt : DateTime
    }

    class Cart {
        id : int
        user : User
        cartItem : Book
        addAt : DateTime
    }

    class Order {
        id : int
        user : User
        orderItems : Book
        totalAmount : int
        status : string
        createdAt : DateTime
    }

    class ResetPasswordRequest {
        id : int
        user : User
        selector : string
        hashedToken : string
        requestedAt : DateTime
        expiresAt : DateTime
    }

    User "1" -- "1..*" Address : has
    User "1" -- "1..*" ResetPasswordRequest : requests
    User "1" -- "1..1" Cart : has
    User "1" -- "1..*" Order: make
    Book "1" -- "1..n" Cart: include 
    Book "1" -- "1..n" Order: include
}

@enduml
